---
- name: STEP 1 - Create site root
  file: state=directory path=/home/{{user}}/www/{{domain}}/{{version}} owner={{user}} group=www-data mode=755 recurse=yes

- name: STEP 2 - Upload site content
  synchronize: src={{wwwroot}}/ dest=/home/{{user}}/www/{{domain}}/{{version}} recursive=yes archive=no mode=push group=yes

- name: STEP 3 - Update site permissions
  file: state=directory path=/home/{{user}}/www/{{domain}}/{{version}} owner={{user}} group=www-data mode=755 recurse=yes

- name: STEP 4 - Set as latest version
  file: src=/home/{{user}}/www/{{domain}}/{{version}} dest=/home/{{user}}/www/{{domain}}/latest state=link owner={{user}} group=www-data

- name: STEP 5 - Add the vhost
  template: src=vhost.j2 dest=/etc/nginx/sites-available/{{domain}}

- name: STEP 6 - Enable website
  file: src=/etc/nginx/sites-available/{{domain}} dest=/etc/nginx/sites-enabled/{{domain}} state=link
  notify: restart nginx
