style:
- text-color: $carmel-color-white
- border-color: $carmel-color-white
- background-color: $carmel-color-material-light-blue-300
- link-color: $carmel-color-white
text:
  title: VIDEO_TITLE
  details: VIDEO_DETAILS
  button: VIDEO_BUTTON
  links: VIDEO_LINK
